CREATE DATABASE Tickets;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT (GETUTCDATE()),
    UpdatedAt DATETIME DEFAULT (GETUTCDATE()),
);

CREATE TABLE TicketStatus (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
);

INSERT INTO TicketStatus (Name) VALUES ('PENDING'), ('IN PROGRESS'), ('CLOSED');


CREATE TABLE Ticket (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    StatusId INT NOT NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT (GETUTCDATE()),
    UpdatedAt DATETIME DEFAULT (GETUTCDATE()),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (StatusId) REFERENCES TicketStatus(Id)
);

SELECT * FROM TicketStatus;

SELECT * FROM Users;

SELECT * FROM Ticket;